import Link from "next/link";
import { ArrowRight, ArrowUpRight, Github, Play, LockKeyhole, Globe2, Radar, ListChecks } from "lucide-react";
import { person, applications } from "@/content/portfolio";
import { ContactSection, ExternalLink } from "@/components/shared";
import { RecentWork } from "@/components/recent-work";

export const dynamic = "force-dynamic";
export default function HomePage() {
  const icons = [Radar, Globe2, ListChecks];
  return <><section className="hero blueprint-grid"><div className="site-container hero-grid"><div className="hero-copy"><div className="eyebrow line-label">SENIOR FULL-STACK ENGINEER</div><h1>Mohamed<br /><span>Shez.</span></h1><h2>Built with intent.<br />Maintained with care.</h2><p>{person.introduction}</p><div className="actions"><Link href="/projects" className="button primary">Explore my projects <ArrowUpRight size={18} /></Link><Link href="/about" className="button">Get to know me <ArrowRight size={18} /></Link></div><div className="tech-tags">{person.technologies.map(tech => <span key={tech}>{tech}</span>)}</div></div><div className="hero-aside"><div className="drawing"><div className="drawing-caption"><span>FIG. 01 / THE BUILDER</span><span>MS—01</span></div><div className="monogram" aria-hidden="true"><div className="construction-circle" /><span>{"{"}<b>ms</b>{"}"}</span><small>IDEA → CODE → PRODUCTION</small></div><div className="nameplate"><div><small>ENGINEER</small><strong>Mohamed Shez</strong></div><div><small>FOCUS</small><strong>Full-stack systems</strong></div></div></div><div className="personal-note"><span className="eyebrow">Beyond the editor</span><p>PC game-server admin. Dad of two.<br />Always something to build.</p></div></div></div></section>
  <div className="domain-strip"><div className="site-container"><span className="mono">OPEN A LIVE APP</span>{applications.map(app => <a key={app.slug} href={app.url} target="_blank" rel="noopener noreferrer">{new URL(app.url).hostname}<ArrowUpRight size={14} /></a>)}</div></div>
  <section className="section site-container"><div className="section-heading"><div><span className="eyebrow">01 / IN PRODUCTION</span><h2>Software you can use.</h2></div><Link className="text-link" href="/projects">Complete project index <ArrowRight size={17} /></Link></div><article className="featured-project"><div className="featured-identity"><div className="feature-meta"><span>MARKETPLACE / LATVIA</span><span>LIVE PRODUCT</span></div><div className="kash-word">KASH<span>.lv</span></div><div className="feature-baseline"><span>THE PRODUCT & THE SYSTEMS BEHIND IT</span><ArrowUpRight size={27} /></div></div><div className="featured-copy"><span className="eyebrow">DEVELOPED & MAINTAINED BY ME</span><h3>A marketplace.<br />And everything behind it.</h3><p>{applications[0].summary}</p><dl className="project-facts"><div><dt>Responsibility</dt><dd>Development & maintenance</dd></div><div><dt>Environments</dt><dd>Production + development</dd></div><div><dt>Source</dt><dd><LockKeyhole size={13} />Private repository</dd></div></dl><div className="actions"><ExternalLink className="button primary" href="https://kash.lv">Visit KASH.lv</ExternalLink><Link className="text-link" href="/work/kash-lv">Explore the project <ArrowRight size={16} /></Link></div></div></article><div className="live-app-grid">{applications.slice(1).map((app, i) => { const Icon = icons[i]; return <article key={app.slug} className="live-app"><div className="card-topline"><span className="mono">{app.category}</span><Icon size={26} /></div><h3><Link href={`/work/${app.slug}`}>{app.name}</Link></h3><p>{app.summary}</p><div className="live-app-actions"><ExternalLink href={app.url}>{new URL(app.url).hostname}</ExternalLink><Link className="text-link" href={`/work/${app.slug}`}>Project details <ArrowRight size={15} /></Link></div></article>; })}</div></section>
  <RecentWork />
  <section className="about-band"><div className="site-container about-band-grid"><div><span className="eyebrow">03 / THE PERSON BEHIND THE CODE</span><h2>Engineer by profession.<br />Builder by nature.</h2><Link className="text-link" href="/about">More about me <ArrowRight size={17} /></Link></div><div className="about-facts"><div><span className="eyebrow">CORE STACK</span><h3>React · Next.js · TypeScript</h3><p>Interfaces, applications, and the systems that support them.</p></div><div><span className="eyebrow">MY APPROACH</span><h3>Build. Refine. Maintain.</h3><p>Hands-on ownership beyond the first release.</p></div><div><span className="eyebrow">OUTSIDE WORK</span><h3>Game servers & family life</h3><p>PC game-server administrator. Dad of two.</p></div></div></div></section>
  <section className="section site-container elsewhere"><div className="channel-card"><span className="eyebrow">PLAY://</span><strong>ShazeAn</strong><Play size={32} /></div><div><span className="eyebrow">04 / ELSEWHERE</span><h2>A little more of my world.</h2><p>Find me on YouTube as @ShazeAn.</p><ExternalLink className="button primary" href={person.youtube}>Visit my YouTube channel</ExternalLink></div></section>
  <section className="site-container github-band"><div><span className="eyebrow">05 / OPEN THE SOURCE</span><h2>My GitHub, connected.</h2><p>Public projects, experiments, and the work in between.</p></div><a href={person.github} className="github-profile" target="_blank" rel="noopener noreferrer"><Github size={32} /><span><strong>mohamedshez</strong><small>github.com/mohamedshez</small></span><ArrowUpRight size={21} /></a></section><ContactSection /></>;
}
